### ISSUE TITLE
1st assignment of Yuliya Androsova

### ISSUE THREAD

**Issue by YuliyaAndrosova** [szabgab/wis-python-course-2024-11#12]
Link to my website: https://yuliyaandrosova.github.io/
Link to my repository:https://github.com/YuliyaAndrosova/yuliyaandrosova.github.io

**Comment by szabgab** [comment]
The repository name is incorrect, it should be based on your username.

**Comment by liroh99** [comment]
Very nice! 
You can now add more information and play around with the github page features.
