### ISSUE TITLE
Day05 by Santiago

### ISSUE THREAD

**Issue by santiagomonl** [szabgab/wis-python-course-2024-11#147]
[Day 05](https://github.com/santiagomonl/python-assignments/tree/main/day05)

Specifically the [Sequence counter](https://github.com/santiagomonl/python-assignments/blob/main/day05/Sequence_nucleotide_counter3.py), the [Test](https://github.com/santiagomonl/python-assignments/blob/main/day05/test_sequence_nucleotide_counter3.py), and the [Dataset file](https://github.com/santiagomonl/python-assignments/blob/main/day05/Datasets.ipynb)

**Comment by HadarKlimovski** [comment]
nice job (💯
