### ISSUE TITLE
Project proposal - Lihi Erez

### ISSUE THREAD

**Issue by Lihierez** [szabgab/wis-python-course-2024-11#156]
https://github.com/Lihierez/qPCR-Results-Analysis/blob/main/README.md

@liroh99

**Comment by liroh99** [comment]
Hi Lihi, the idea sounds great, you can go ahead and begin to work on it if you wish. 
I actually wrote a program like this for my final project, so you can take a look to get ideas if you need.
In regards to the structure of the proposal you can take a look at how I wrote it: 
https://github.com/liroh99/qPCR_data_analysis
I think you should add a bit more of the details of what the project will require: which parameters, which files, how the program will be run, what requirements will be needed. You will continue to grow this as your project grows, so you don't need to specify everything, but understanding what your code needs will assist you in building it. 
Good luck!
