### ISSUE TITLE
Day 6 By Lior Lin

### ISSUE THREAD

**Issue by LiorLin** [szabgab/wis-python-course-2024-11#160]
Hi, this is the link for my day06 folder : https://github.com/LiorLin/Course_Assignments/tree/main/day06

Right now it consists of the jupyter notebook file only.
 I will add the ncbi.py file as soon as we are able to overcome the biopython downloading issue together.

@HadarKlimovski 

Nice week,
Lior

**Comment by LiorLin** [comment]
Hi, 
I managed to work with Biopython in google collab for means of this assignment, 
and uploaded a ncbi.py file. 

I didn't make it a command line tool, as I worked on a notebook and not a terminal, 
but I could theoretically tranform it into a command line tool using the sys library (with sys.argv). 

@HadarKlimovski 

Thanks for your help !
Lior

**Comment by HadarKlimovski** [comment]
very good job lior (💯
