### ISSUE TITLE
Project Proposal by Aishwarya Singh

### ISSUE THREAD

**Issue by Aish16032001** [szabgab/wis-python-course-2024-11#172]
Here is the repository for Project Proposal. Let me know if you have any suggestions.
https://github.com/Aish16032001/Molecular-Dynamics-Structure-Analysis
@liroh99 
Thankyou

**Comment by liroh99** [comment]
Hi, this sounds very practical and well thought out. When you're ready, you can start writing the project.
For planning how to execute the program, you can look at projects from previous years, this is mine for example:
https://github.com/liroh99/qPCR_data_analysis
As your project progresses, remember the proposal will become the user documentation- document the parameters that are being used, how to install the dependencies needed, how to run the code, how the data is processed, and anything else the user will need to run the code smoothly. 
Good luck :)
