### ISSUE TITLE
1st Assignment of Stav Ohayon

### ISSUE THREAD

**Issue by Stavoh** [szabgab/wis-python-course-2024-11#18]
My website: https://stavoh.github.io/
My repository: https://github.com/Stavoh/stavoh.github.io

**Comment by szabgab** [comment]
You need to rename the repository to be USERNAME.github.io so it will be seen at https://stavoh.github.io/

**Comment by Stavoh** [comment]
> You need to rename the repository to be USERNAME.github.io so it will be seen at https://stavoh.github.io/

Is it good now?

**Comment by szabgab** [comment]
You tell me, when you click on the link I pasted, does it show your site?

**Comment by Stavoh** [comment]
No 😭

**Comment by liroh99** [comment]
Have you tried renaming your repository to stavoh.github.io? Since I still see it as Stavoh

**Comment by Stavoh** [comment]
> Have you tried renaming your repository to stavoh.github.io? Since I still see it as Stavoh

Yes. It's fixed now, and the original comment in this issue was edited accordingly.
Thanks

**Comment by HadarKlimovski** [comment]
nice (:
