### ISSUE TITLE
Project proposal By Romi Brody

### ISSUE THREAD

**Issue by romizb** [szabgab/wis-python-course-2024-11#182]
![BFE 🐾](https://github.com/romizb/Big-Floof-Energy/blob/main/README.md) 

@liroh99

**Comment by liroh99** [comment]
Nice touch adding the pictures and gifs, I'm sure this will be very useful for your everyday tasks. 
I'm curious to see where this idea takes you and how it will look :) 
If you run into problems, feel free to write me an email :)
