### ISSUE TITLE
Project proposal by Artem Dubovetskyi

### ISSUE THREAD

**Issue by artemD7** [szabgab/wis-python-course-2024-11#183]
https://github.com/artemD7/PubRanker

@liroh99

**Comment by liroh99** [comment]
Hi Artem, good job on the creative idea. When you're ready, you can start writing the project. 
For planning how to execute the program, you can look at projects from previous years, this is mine for example: 
https://github.com/liroh99/qPCR_data_analysis
You can now add a bit about how the data will be processed, which parameters it will take, the command that will run the program, the dependencies it will require and such. 
Of course, not all of this is necessary and will be changed as you write the code itself, but it will help you begin to plan how the code will be written. 
Good luck :)
