### ISSUE TITLE
Project proposal by Anastasiia Mamaeva

### ISSUE THREAD

**Issue by AnastasiiaMamaeva** [szabgab/wis-python-course-2024-11#187]
I've written proposal: https://github.com/AnastasiiaMamaeva/Sequence_parser

The final app might be slightly different from initial proposal, so I will be updating it while writing code

@liroh99

**Comment by liroh99** [comment]
Hi Anastasiia, nice idea. Very useful in my personal experience. 
I would suggest once you have a clearer idea of your code, update the readme to include the dependencies the code will need, the way to run the program, how the test will be run, etc. 
You can look at my project to get an idea of how the final version should look like:
https://github.com/liroh99/qPCR_data_analysis
Good luck!
