### ISSUE TITLE
1st assignment of ADI MOSKOVITS

### ISSUE THREAD

**Issue by AdiMosko** [szabgab/wis-python-course-2024-11#2]
My Git-HUB account [AdiMosko](https://github.com/AdiMosko).
https://github.com/AdiMosko

My repository [AdiMoko.github.io](https://github.com/AdiMosko/AdiMoko.github.io).
https://github.com/AdiMosko/AdiMoko.github.io

My WebSite [AdiMoskovits](https://adimosko.github.io/AdiMokovits/).
https://adimosko.github.io/AdiMokovits/

***
for some reson the pictures which appear on the ReadMe file correctly, does not appear on the actual site.
would appreciate help in this manner
thanks
Adi
***

**Comment by HadarKlimovski** [comment]
try to use this line for you images :

![](/Adi-9.png)

**Comment by HadarKlimovski** [comment]
try to use this line for you images :![](/image_name.png)

**Comment by HadarKlimovski** [comment]
> try to use this line for you images :![](/image_name.png)

**Comment by AdiMosko** [comment]
Hi Hadat
thank you for the comment
I am familiar with this syntax, 
but i wanted to create a unified and more designed look by adding pictures with defined width (45px)
and thus incorporated the HTML syntax for it as Gabore suggested in the class.

in the Read me the pictures appear fine, but on the web page thay are missing.
suggesting it is something woth the picture URL path maybe?
since i do not have much experience in HTML programming or programming al all for that matter, i do not know how to proceed.

cuould not find much on the web on that matter either (probably did not know how to llok for it correctly).

if there will be no solution I will go back to use the regular markdwn syntax as you suggested.

**Comment by HadarKlimovski** [comment]
Hi, it's really nice that you try interesting things! But I don't know the way you used it, only what was taught in class.
I suggest you look at pages from previous years, maybe use your approach.

good luck! (:

**Comment by szabgab** [comment]
It also seems that the name of the repository is incorrect. It should be `adimosko.github.io` so the site will be at https://adimosko.github.io/

**Comment by AdiMosko** [comment]
I renamed it to be more informative and intuitive, since I intend to add
more pages in the future and link them all to this main page.
 thus the name of the web-page is different:

[image: image.png]

__________________________________

Adi Moskovits

57-B Har-Masadah st., Ashdod, Israel (zip:77711)
Cell: 972-50-8787990
Tel/Fax: 153-50-8787990
Linked-In: https://www.linkedin.com/in/adimoskovits
E-mail: ***@***.***
__________________________________

**Comment by AdiMosko** [comment]
**Well i give up!**

After all issues with HTML code blocks, I decided to scrap the work and start over.
1-copied the code to notepad file
2-deleted the previous version of the repository
3-resized pictures to specific 450px width on-line (https://www.iloveimg.com/resize-image)
4-uploaded the new resized picture files to the repository
5-copied the previous code, and changed the html-picture blocs to the simple markdown sintax
6-committed these changes.

**now- the page is wmpty!**

![image](https://github.com/user-attachments/assets/84c75ced-c65e-4c3d-a38b-24763b979fed)

**although Red me gile seems OK...**

![image](https://github.com/user-attachments/assets/ba135e81-5ef5-4f5d-8110-b3a0fd5a38ff)

***

these are the updated links:

[My Git-HUB account](https://github.com/AdiMosko).
https://github.com/AdiMosko

[My repository](https://github.com/AdiMosko/AdiMosko.github.io).
https://github.com/AdiMosko/AdiMosko.github.io

[My WebSite](https://adimosko.github.io/).
https://adimosko.github.io/

***

I think I will leave this as it is for now.
I will aproach you at the begining or end of the next class and will try to understand what the hell is happening here
sorry

**Comment by szabgab** [comment]
If you visit https://github.com/AdiMosko/AdiMosko.github.io/blob/main/Adi-Teach.jpg , one of the links to your pictures, you can notice that is not **only** the picture. That link is actually a page on GitHub that also happen to include the picture.

Probably a better approach would be to use only the name of the file like this: `![](Adi-Teach.jpg`

**Comment by AdiMosko** [comment]
Thanks
It Works!!!

**Comment by liroh99** [comment]
Good work on your site, lots of information and effort. 
Next, I would suggest you also play around with different themes to make the site look better.
Good luck!
