### ISSUE TITLE
1st assignment of Maytal Katz

### ISSUE THREAD

**Issue by maytalkatz** [szabgab/wis-python-course-2024-11#21]
Link to my website:  https://maytalkatz.github.io/
Link to my repository: https://github.com/maytalkatz/maytalkatz.github.io

**Comment by HadarKlimovski** [comment]
cool.
you can improve you page and ,make it nicer.
You can look at student pages from the last semester:
https://github.com/szabgab/wis-python-course-2024-04

**Comment by AnastasiiaMamaeva** [comment]
Wow! Really lovely website :3
But if you want to improve it, you can try to add a background
Good luck!

**Comment by szabgab** [comment]
@AnastasiiaMamaeva , please open an issue on the repository of that web site and not a comment on the repository of the course.

**Comment by AnastasiiaMamaeva** [comment]
I did it for two other students and now cannot find those issues, but I'll do it again

**Comment by szabgab** [comment]
This lists all the issues you opened: https://github.com/search?q=author%3AAnastasiiaMamaeva&type=issues
