### ISSUE TITLE
1st assignment of Grigorii Rubinovskii 

### ISSUE THREAD

**Issue by GRIGORII9999** [szabgab/wis-python-course-2024-11#22]
https://grigorii9999.github.io/grigoriirub.github.io/

**Comment by GRIGORII9999** [comment]
https://github.com/GRIGORII9999/grigoriirub.github.io

**Comment by HadarKlimovski** [comment]
i cant see your page, please fix it @GRIGORII9999 

You can look at student pages from the last semester:
https://github.com/szabgab/wis-python-course-2024-04

**Comment by grigoriirub** [comment]
> i cant see your page, please fix it @GRIGORII9999
> 
> You can look at student pages from the last semester: https://github.com/szabgab/wis-python-course-2024-04

Hi! I fixed it, please close the issue

**Comment by HadarKlimovski** [comment]
@szabgab can you add his page to the course page? thank you

**Comment by szabgab** [comment]
added
