### ISSUE TITLE
1st assignment of Anatoly Kustanovich

### ISSUE THREAD

**Issue by AnatolyKustanovich** [szabgab/wis-python-course-2024-11#27]
repository:
https://github.com/T-olik/AnatolyKustanovich.github.io

website:
https://anatolykustanovich.github.io/

**Comment by liroh99** [comment]
The name of the repository needs to be USERNAME.github.io, that way we can see it when we type: https://T-olik.github.io

**Comment by AnatolyKustanovich** [comment]
I changed a website name
Best regards,
Anatoly

**Comment by HadarKlimovski** [comment]
nice (:
