### ISSUE TITLE
1st assignment of Catalina Donic

### ISSUE THREAD

**Issue by CatalinaDonic** [szabgab/wis-python-course-2024-11#28]
My website is:
https://catalinadonic.github.io/.

My repository is:
https://github.com/CatalinaDonic/CatalinaDonic.github.io.

**Comment by HadarKlimovski** [comment]
cool.
you can improve you page and ,make it nicer.
You can look at student pages from the last semester:
https://github.com/szabgab/wis-python-course-2024-04
