### ISSUE TITLE
1st assignment of Maxim Kuryachiy

### ISSUE THREAD

**Issue by MaximKuryachiy** [szabgab/wis-python-course-2024-11#29]
[My repository](https://github.com/MaximKuryachiy/maximkuryachiy.github.io) <br>
[My website](https://maximkuryachiy.github.io/)

**Comment by HadarKlimovski** [comment]
cool.
You can improve your page and make it nicer.
You can look at your friends' pages and from the previous semester:
https://github.com/szabgab/wis-python-course-2024-04

**Comment by AnastasiiaMamaeva** [comment]
Really nice website!
I would suggest you, however, to change the size of image: it seems to be too wide. You can do it in photoshop or without any changes of photo using HTML code: https://www.w3schools.com/tags/att_img_width.asp
Good luck!

**Comment by szabgab** [comment]
@AnastasiiaMamaeva , The idea is to open an issue on the GitHub repository of the web site and not to comment on the (already closed) issue in the central repository of the course.
