### ISSUE TITLE
Day 2 by Guy Haim 

### ISSUE THREAD

**Issue by HaimGuy** [szabgab/wis-python-course-2024-11#33]
Hi, 
Here is my 2nd day assignment: 
https://github.com/HaimGuy/assignments/tree/Day02

**Comment by szabgab** [comment]
You created a branch called Day02 instead of creating a folder called Day02 in the main branch. Please fix it.

**Comment by HadarKlimovski** [comment]
hi guy (:

create a folder named Day02, and then put the day2.ipynb in it.
good day (: @HaimGuy

**Comment by HaimGuy** [comment]
Thanks, I believe I’ve fixed it. Here: 
https://github.com/HaimGuy/Assignments
