### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by AnastasiiaMamaeva** [szabgab/wis-python-course-2024-11#43]
Really nice website!
I would suggest you, however, to change the size of image: it seems to be too wide. You can do it in photoshop or without any changes of photo using HTML code: https://www.w3schools.com/tags/att_img_width.asp
Good luck!

**Comment by Stavoh** [comment]
Thanks! Would love to get instructions on how to do it tomorrow in class.

**Comment by szabgab** [comment]
You have the link above for the HTML and we won't cover Photoshop in our course, but I am sure you can find plenty of explanations how to do this.
