### ISSUE TITLE
day 2 by Anatoly Kustanovich

### ISSUE THREAD

**Issue by AnatolyKustanovich** [szabgab/wis-python-course-2024-11#47]
Link to the repository with assignments of Day 2: https://github.com/AnatolyKustanovich/python-assignments

**Comment by HadarKlimovski** [comment]
in the rectangle.py you need to remove :

Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>>

**Comment by AnatolyKustanovich** [comment]
Thank You! Corrected.

**Comment by AnatolyKustanovich** [comment]
@hadarklimovski

**Comment by HadarKlimovski** [comment]
good job! (💯
