### ISSUE TITLE
1st assignment of Aishwarya Singh

### ISSUE THREAD

**Issue by Aish16032001** [szabgab/wis-python-course-2024-11#5]
My repository : https://github.com/Aish16032001/Aish16032001.github.io 
My website : https://Aish16032001.github.io/

**Comment by szabgab** [comment]
The name of the repository must be  USERNAME.github.io, so the page will show up at https://aish16032001.github.io/
Please rename the repo.

**Comment by Aish16032001** [comment]
Thankyou for the suggestion
