### ISSUE TITLE
day2 by Yulia Eriukova

### ISSUE THREAD

**Issue by yuliaerk** [szabgab/wis-python-course-2024-11#61]
https://github.com/yuliaerk/python-assignments

**Comment by HadarKlimovski** [comment]
in day2.ipynb you have an error :
NameError: name 'math' is not defined

you need to import the package if you want it to work : 
'''''
import math as ..
"""

**Comment by yuliaerk** [comment]
> in day2.ipynb you have an error : NameError: name 'math' is not defined
> 
> you need to import the package if you want it to work : ''''' import math as .. """

thanks, I fixed it, @HadarKlimovski

**Comment by HadarKlimovski** [comment]
good job (👍
