### ISSUE TITLE
Day02 by Romi (Ruchama) Brody

### ISSUE THREAD

**Issue by romizb** [szabgab/wis-python-course-2024-11#63]
https://github.com/romizb/python-assignments

**Comment by liroh99** [comment]
Hi Romi, 
Make sure in the jupyter notebook to upload a file ipynb which is a python notebook file, and not an html file.

**Comment by romizb** [comment]
Thank you for the comment.
I created a new repository with the requested changes, hope it is satisfactory.
See you in class!

https://github.com/romizb/python_assignments

**Comment by szabgab** [comment]
This time I'll replace the link to your repo here https://github.com/szabgab/wis-python-course-2024-11 but please, next time don't start a new repo. Just fix the files in the existing one. If you don't know how, ask.
