### ISSUE TITLE
1st assignment of Anastasiia Mamaeva

### ISSUE THREAD

**Issue by AnastasiiaMamaeva** [szabgab/wis-python-course-2024-11#7]
site https://anastasiiamamaeva.github.io
repository https://github.com/AnastasiiaMamaeva/anastasiiamamaeva.github.io

**Comment by liroh99** [comment]
Good job! 
Next, I would suggest proofreading your site and to play around with themes and layouts to add more depth

**Comment by AnastasiiaMamaeva** [comment]
Thank you for a feedback! I changed website text a little bit and add a config file with a theme.
