### ISSUE TITLE
1st assignment of Sima Glicksman

### ISSUE THREAD

**Issue by simiglicks** [szabgab/wis-python-course-2024-11#8]
Link to website: [https://simiglicks.github.io](https://simiglicks.github.io/)
Link to repository: [https://github.com/simiglicks/simiglicks.github.io](https://github.com/simiglicks/simiglicks.github.io)

**Comment by liroh99** [comment]
Good job! 
If you wish, you can play around with themes to improve the aesthetic of the site.
