### ISSUE TITLE
day 3 Grigorii Rubinovskii 

### ISSUE THREAD

**Issue by grigoriirub** [szabgab/wis-python-course-2024-11#86]
https://github.com/grigoriirub/Assignments/tree/main/day3

@HadarKlimovski

**Comment by HadarKlimovski** [comment]
good!

by the way, when you  trying to generate a plot for your calculation, you encountered a NameError: name 'plt' is not defined.
To resolve this issue and display the plot, you need to **pip install matplotlib** and then **import matplotlib.pyplot as plt**
