### ISSUE TITLE
Day 1 : Tal Sharon

### ISSUE THREAD

**Issue by SharonTal** [szabgab/wis-python-course-2024-11#94]
Link to GitHub pages: https://github.com/SharonTal/TalSharon.github.io/tree/main
Link to GitHub rep : https://github.com/SharonTal/TalSharon.github.io.git
Link to website  : https://sharontal.github.io/TalSharon.github.io/

**Comment by HadarKlimovski** [comment]
Hi Tal, where is your website? I don't see it.
Put a link in the comment if you created one.
I see that you are missing a yml file. I suggest you look at pages from previous years to get a feel for how it works.
https://github.com/szabgab/wis-python-course-2024-04

**Comment by liroh99** [comment]
Nice, make sure to add more information and add a picture (doesn't have to be of yourself). 
Look at other websites to experiment with different themes of the github pages.

**Comment by szabgab** [comment]
You need to change the repository to be the same as your GitHub username. right now your username is SharonTal and the repository is TalSharon.github.io.  You have to change it to SharonTal.github.io You can do so in the Settings of the repo

**Comment by SharonTal** [comment]
@szabgab , @liroh99 , @HadarKlimovski  
Thanks all for the comments. 
fixed :
https://sharontal.github.io/

**Comment by liroh99** [comment]
looks great 👍
